title: <p align="center"> Anandhakumar Dharmalingam </p>
logo: /assets/img/Anandhakumar D.jpg

description:
  <p align="center">
  <a href="/assets/Anandhakumar_D_Resume_2021.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/anandha-kumar-a4152a58/">LinkedIn</a> |
  <a href="https://github.com/Anandhakumar1">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
